## Input files
##---------------------------------------------------------------------------------------------
## Path to code
codeP: /home/fiona/phd/microbes/simulation/wflow_saliva/code

## Output files
##---------------------------------------------------------------------------------------------
## Path to output (data, figures)
outPD: /home/fiona/phd/microbes/simulation/wflow_saliva/output/RData
outPF: /home/fiona/phd/microbes/simulation/wflow_saliva/output/Figure

## Path to log files
RoutP: /home/fiona/phd/microbes/simulation/wflow_saliva/Rout

## R setup
##---------------------------------------------------------------------------------------------
## Specify your own R installation (then you have to set the path to your library in the .Renviron file)
Rbin: /usr/local/R/R-3.6.1/bin/R
##---------------------------------------------------------------------------------------------

