## Input files
##---------------------------------------------------------------------------------------------
## Path to codes (the code folder)
codeP: code

## Output files
##---------------------------------------------------------------------------------------------
## Path to output (data, figures)
outPD: output/RData
outPF: output/Figure

## Path to log files
RoutP: /home/fiona/treeclimbR_article/cytof/DA/Rout

## R setup
##---------------------------------------------------------------------------------------------
## Specify your own R installation (then you have to set the path to your library in the .Renviron file)
Rbin: /usr/local/R/R-3.6.1/bin/R
##---------------------------------------------------------------------------------------------
