## Input files
##---------------------------------------------------------------------------------------------
## Path to codes (the code folder)
codeP: /home/fiona/treeclimbR_article/cytof/DS/code

## Output files
##---------------------------------------------------------------------------------------------
## Path to output (data, figures)
outPD: /home/fiona/treeclimbR_article/cytof/DS/output/RData
outPF: /home/fiona/treeclimbR_article/cytof/DS/output/Figure
## Path to log files
RoutP: /home/fiona/treeclimbR_article/cytof/DS/Rout

## R setup
##---------------------------------------------------------------------------------------------
## Specify "True" if R should be installed in a conda environment or "False" if you want to use 
## your own R installation (then you have to set the path to your library in the .Renviron file)
Rbin: /usr/local/R/R-3.6.1/bin/R
##---------------------------------------------------------------------------------------------
