library(stringr)
library(TreeSummarizedExperiment)
library(dplyr)

# folder path: store .res files generated by lefse
pathR <- "lefse/output/res"

# load tree
load("lefse/output/tree.RData")

# a function to remove ancestors
rm_ancestor <- function(node, tree) {
    if (!length(node)) {
        node
    } else {
        loc <- node
        # each row is a path connecting a leaf to the root
        mat <- matTree(tree = tree)
        # which paths are detected nodes on?
        lat <- lapply(loc, FUN = function(x){
            which(mat == x, arr.ind = TRUE)
        })
        lat1 <- do.call(rbind.data.frame, lat)
        lat1 <- lat1 %>% 
            group_by(row) %>% 
            arrange(col) %>%
            as.matrix()
        
        # nodes in paths where exist only one detected nodes
        lat2 <- lat1[!duplicated(lat1[, 1]), ]
        k2 <- unique(mat[lat2])
        # nodes in paths where exist more one detected nodes
        # (node that is closest to the leaf level not included)
        lat3 <- lat1[duplicated(lat1[, 1]), ]
        k3 <- unique(mat[lat3])
        
        # remove nodes 
        kk <- intersect(k2, k3)
        setdiff(loc, kk)  
    }
}
# a function to extract nodes identified by lefse
loc_fun <- function(x, tree, reso = "high") {
    res <- read.delim(file.path(pathR, x), header=FALSE)
    colnames(res) <- c("taxon", "log.max.pct", "direction", "lda", "p.value")
    
    suppressWarnings({
        res_f <- res %>%
            mutate(p.value = as.numeric(as.character(p.value))) %>%
            filter(!is.na(p.value))
        
    })
    
    nodeS <- gsub(pattern = ".*\\.", replacement = "", x = res_f$taxon)
    nodeS <- transNode(tree = tree, node = nodeS)
    
    if (reso == "high") {
        rm_ancestor(node = nodeS, tree = tree)
    } else {
        nodeS
    }
    
}

# all .res files
files <- list.files(pathR)

# each file stores results of a simulation at a specified FDR
df <- data.frame(file = files) %>%
    mutate(fdr = str_match(file, ":(.*?)\\.res")[,2],
           fdr = as.numeric(as.character(fdr)),
           main = gsub(pattern = "_rep.*", "", file),
           rep = str_match(file, "_rep(.*?):")[,2]) 

# extract nodes from each file
df_scene <- split(df, df$main)    
out_lefse_high <- lapply(df_scene, FUN = function(x) {
    xx <- split(x, x$fdr)
    xy <- lapply(xx, FUN = function(y){
        lapply(y$file, FUN = function(z){
            loc_fun(z, tree = tree, reso = "high")
        })
    })
    xy
})

out_lefse_low <- lapply(df_scene, FUN = function(x) {
    xx <- split(x, x$fdr)
    xy <- lapply(xx, FUN = function(y){
        lapply(y$file, FUN = function(z){
            loc_fun(z, tree = tree, reso = "low")
        })
    })
    xy
})
save(out_lefse_low, out_lefse_high,
     file = file.path(gsub("res", "nodes", pathR), "out_lefse.RData"))



# fc <- metadata(tse)$FC
# leaf_da <- list(up = names(fc)[fc > 1],
#                down = names(fc)[fc < 1])
# signal_da <- lapply(leaf_da, FUN = function(x) {
#     xx <- signalNode(tree = tree, node = x)
#     dx <- findOS(tree = tree, node = xx, only.leaf = FALSE, self.include = TRUE)
#     unlist(dx)
# })
# df_signal <- printNode(tree = tree, type = "all") %>% 
#     dplyr::rename(node = nodeNum) %>%
#     select(node) %>%
#     mutate(type = ifelse(node %in% signal_da[[1]], "up",
#                          ifelse(node %in% signal_da[[2]], "down", "same")))
# head(df_signal)
# 
# library(ggtree)
# ggtree(tree, layout = "circular",
#        branch.length = "none") %<+% df_signal +
#     aes(color = type) +
#     scale_color_manual(values = c("same" = "grey",
#                                   "up" = "orange",
#                                   "down" = "blue")) +
#     geom_point2(aes(subset = (node %in% nodeS)), color = "red")
