suppressPackageStartupMessages({
    library(ape)
    library(dplyr)
    library(TreeHeatmap)
    library(TreeSummarizedExperiment)
    library(ggtree)  
    library(stringr)
})

# load data
mainPath <- "/Volumes/fiona/phd/treeclimbR_article/simulation_microbe"
dataFile <- c("BS_sp10_sim5_r4_L2.RData",
              "BS_sp25_sim5_r4_L2.RData",
              "BS_sp50_sim5_r4_L2.RData",
              "SS_sp10_sim5_r4_pct0.4_L2.RData",
              "SS_sp25_sim5_r4_pct0.4_L2.RData",
              "SS_sp50_sim5_r4_pct0.4_L2.RData",
              "US_sp10_sim5_r4_L2.RData",
              "US_sp25_sim5_r4_L2.RData",
              "US_sp50_sim5_r4_L2.RData")
outFile <- file.path("lefse", "output", "txt",
                     gsub(pattern = ".RData", ".txt", dataFile))
dataPath <- file.path(mainPath, "output/RData/DataPrep", dataFile)


# scene
scene <- gsub(pattern = "_.*", "", dataFile)
ns <- as.numeric(str_match(dataFile, "sp(.*?)_sim")[, 2])

# ------------------------------- data format ---------------------------------
for (i in seq_along(dataFile)) {
    message(dataPath[i])
    # convert data into a format required by lefse
    load(dataPath[i])
    
    # hierarchy
    tree <- rowTree(tse)
    if (i == 1) {
        save(tree, file = file.path("lefse/output", "tree.RData"))
    }
    path <- matTree(tree = tree)
    pathL <- lapply(seq_len(nrow(path)), FUN = function(x) {
        xx <- path[x, ]
        xx <- xx[!is.na(xx)]
        tx <- transNode(tree = tree, node = xx, use.alias = TRUE)
        paste(rev(tx),collapse = "|")
    })
    
    # tabular data required by lefse
    oo <- transNode(tree = tree, node = path[, 1], use.alias = TRUE)
    lse <- tse[rowLinks(tse)$isLeaf, ]
    
    # repetitions
    count <- assays(lse)
    class <- colData(lse)$group
    for (j in seq_along(count)) {
       count_j <- count[[j]][oo, ]
       rownames(count_j) <- unlist(pathL) 
       
       df <- rbind.data.frame(
           class,
           colnames(count_j),
           count_j)
       rownames(df) <- c("class", "sample_id", rownames(count_j))
       
       # output
       file_j <- gsub(pattern = "\\.txt", paste0("_rep", j, ".txt"), outFile[i])
       message(file_j)
       write.table(x = df, file = file_j, sep = "\t",
                   row.names = TRUE, col.names = FALSE, quote = FALSE)
    }
}

# ## ============================ output from LEFSe =============================
# ## save files generated by LEfSe (https://huttenhower.sph.harvard.edu/galaxy/)
# ## 1. upload .txt file (e.g., BS_sp10_sim5_r4_L2.txt) as the input file of LEfSe.
# ## 2. run the first two steps of LEfSe 
# ##     A) Format Data for LEfSe 
# ##       class: 'class'; subject: 'sample_id'; normalization: Yes
# ##     B) LDA Effect Size (LEfSe) (Default setting)
# ##       alpha Kruskal-Wallis: 0.05; alpha pairwise Wilcoxon;
# ##       threshold log-LDA score: 2.0
# ##       pairwise comparisons among subclasses: No
# ##       Set the strategy for multi-class : All-against-all(more strict)
# ## 3. save the output file using the same name of the input file
# ##     e.g. if using BS_sp10_sim5_r4_L2.txt in step 1, 
# ##           then output file is BS_sp10_sim5_r4_L2.res
# 
#     
